In [81]:
import pandas as pd
import seaborn as sns
from copy import deepcopy

%matplotlib notebook
import matplotlib
import matplotlib.pyplot as plt

In [82]:
data = pd.read_csv("Greek_Names.csv")

In [83]:
del data['isFemale']

In [84]:
start = 2
end = 4

In [85]:
data = pd.DataFrame(data.Names.str.split('-').tolist(), index = data.isMale).stack()
data = data.reset_index()[[0,'isMale']]
data.columns = ['Names', 'isMale']

In [86]:
data = data.drop(data[data.Names.map(len)<2].index)

In [87]:
data = pd.concat(g for _, g in data.groupby('isMale') if len(g)>1)

In [88]:
data = data.sort_values(by='Names')

In [89]:
data = data.reset_index(drop=True)

In [90]:
data['Frequency'] = data.groupby(['Names', 'isMale'])[['Names']].transform('count')

In [91]:
data.sort_values(by='Names')

                    Names  isMale  Frequency
0                   ΑΑΡΩΝ       1          1
1                    ΑΒΑΓ       1          1
2                 ΑΒΑΓΟΡΙ       1          1
3                   ΑΒΑΙΣ       1          1
4                  ΑΒΕΜΙΡ       1          1
5                  ΑΒΕΡΚΙ       1          1
6                ΑΒΕΡΚΙΟΣ       1          2
7                ΑΒΕΡΚΙΟΣ       1          2
8                  ΑΒΕΡΣΑ       0          1
9                ΑΒΕΣΑΛΩΛ       1          1
10               ΑΒΕΣΑΛΩΜ       1          1
11                   ΑΒΕΤ       1          1
12                  ΑΒΚΟΡ       0          1
13                   ΑΒΝΙ       1          1
14                    ΑΒΡ       1          1
15                 ΑΒΡΑΑΜ       1          2
16                 ΑΒΡΑΑΜ       1          2
17                 ΑΒΡΑΑΜ       0          1
18            ΑΒΡΑΑΜΘΩΜΑΣ       1          1
19                 ΑΒΡΟΒΑ       0          1
20               ΑΒΡΟΚΟΜΗ       0          1
21               ΑΒΡΟΤΕΛΗ       1          1
22               ΑΒΤΑΝΔΙΛ       1          1
23               ΑΒΤΑΝΤΗΛ       1          1
24               ΑΒΤΑΝΤΙΛ       1          1
25                 ΑΓΑΒΝΗ       0          1
26                  ΑΓΑΘΑ       0          1
27             ΑΓΑΘΑΓΓΕΛΟ       1          1
28            ΑΓΑΘΑΓΓΕΛΟΣ       1          1
29                  ΑΓΑΘΗ       1          1
...                   ...     ...        ...
9812            ΧΡΥΣΟΠΗΓΗ       0          1
9813             ΧΡΥΣΟΠΙΑ       0          1
9814            ΧΡΥΣΟΣΤΟΜ       1          1
9815          ΧΡΥΣΟΣΤΟΜΟΣ       1          2
9816          ΧΡΥΣΟΣΤΟΜΟΣ       1          2
9817  ΧΡΥΣΟΣΤΟΜΟΣΓΕΩΡΓΙΟΣ       1          1
9818               ΧΡΥΣΟΥ       0          1
9819              ΧΡΥΣΟΥΛ       0          1
9820             ΧΡΥΣΟΥΛΑ       0          7
9821             ΧΡΥΣΟΥΛΑ       0          7
9822             ΧΡΥΣΟΥΛΑ       0          7
9823             ΧΡΥΣΟΥΛΑ       0          7
9824             ΧΡΥΣΟΥΛΑ       0          7
9825             ΧΡΥΣΟΥΛΑ       1          1
9826             ΧΡΥΣΟΥΛΑ       0          7
9827             ΧΡΥΣΟΥΛΑ       0          7
9828       ΧΡΥΣΟΥΛΑΕΙΡΗΝΗ       0          1
9829     ΧΡΥΣΟΥΛΑΕΛΙΣΑΒΕΤ       0          1
9830    ΧΡΥΣΟΥΛΑΕΥΑΓΓΕΛΙΑ       0          1
9831            ΧΡΥΣΟΥΛΗΣ       1          1
9832           ΧΡΥΣΟΦΙΛΗΣ       1          1
9833            ΧΡΥΣΤΑΛΛΑ       0          1
9834                ΧΡΥΣΩ       0          1
9835                ΧΥΣΕΝ       1          1
9836               ΧΥΣΕΝΙ       1          1
9837                ΩΡΑΙΑ       0          1
9838            ΩΡΑΙΟΖΗΛΗ       0          2
9839            ΩΡΑΙΟΖΗΛΗ       0          2
9840            ΩΡΑΙΟΖΙΛΗ       0          1
9841            ΩΡΑΙΟΖΥΛΗ       0          1

[9842 rows x 3 columns]

In [92]:

# print("12345")
# print(len(data), len(copied))
# copied.drop(copied.index[40:50], inplace=True )
# print(len(data), len(copied))

In [93]:
data.drop_duplicates(keep='first', inplace=True)
data.reset_index(drop=True,inplace =True)

In [94]:
copied = data.copy()
copied

                     Names  isMale  Frequency
0                    ΑΑΡΩΝ       1          1
1                     ΑΒΑΓ       1          1
2                  ΑΒΑΓΟΡΙ       1          1
3                    ΑΒΑΙΣ       1          1
4                   ΑΒΕΜΙΡ       1          1
5                   ΑΒΕΡΚΙ       1          1
6                 ΑΒΕΡΚΙΟΣ       1          2
7                   ΑΒΕΡΣΑ       0          1
8                 ΑΒΕΣΑΛΩΛ       1          1
9                 ΑΒΕΣΑΛΩΜ       1          1
10                    ΑΒΕΤ       1          1
11                   ΑΒΚΟΡ       0          1
12                    ΑΒΝΙ       1          1
13                     ΑΒΡ       1          1
14                  ΑΒΡΑΑΜ       1          2
15                  ΑΒΡΑΑΜ       0          1
16             ΑΒΡΑΑΜΘΩΜΑΣ       1          1
17                  ΑΒΡΟΒΑ       0          1
18                ΑΒΡΟΚΟΜΗ       0          1
19                ΑΒΡΟΤΕΛΗ       1          1
20                ΑΒΤΑΝΔΙΛ       1          1
21                ΑΒΤΑΝΤΗΛ       1          1
22                ΑΒΤΑΝΤΙΛ       1          1
23                  ΑΓΑΒΝΗ       0          1
24                   ΑΓΑΘΑ       0          1
25              ΑΓΑΘΑΓΓΕΛΟ       1          1
26             ΑΓΑΘΑΓΓΕΛΟΣ       1          1
27                   ΑΓΑΘΗ       1          1
28                   ΑΓΑΘΗ       0          2
29              ΑΓΑΘΗΜΑΡΙΑ       0          1
...                    ...     ...        ...
7983          ΧΡΥΣΟΒΑΛΑΝΤΟ       0          1
7984         ΧΡΥΣΟΒΑΛΑΝΤΟΥ       0          4
7985  ΧΡΥΣΟΒΑΛΑΝΤΟΥΔΗΜΗΤΡΑ       0          1
7986          ΧΡΥΣΟΒΑΛΑΝΤΩ       0          2
7987         ΧΡΥΣΟΒΑΝΑΝΤΟΥ       0          1
7988           ΧΡΥΣΟΒΕΡΓΗΣ       0          1
7989           ΧΡΥΣΟΒΕΡΓΗΣ       1          1
7990               ΧΡΥΣΟΠΗ       0          1
7991             ΧΡΥΣΟΠΗΓΗ       0          1
7992              ΧΡΥΣΟΠΙΑ       0          1
7993             ΧΡΥΣΟΣΤΟΜ       1          1
7994           ΧΡΥΣΟΣΤΟΜΟΣ       1          2
7995   ΧΡΥΣΟΣΤΟΜΟΣΓΕΩΡΓΙΟΣ       1          1
7996                ΧΡΥΣΟΥ       0          1
7997               ΧΡΥΣΟΥΛ       0          1
7998              ΧΡΥΣΟΥΛΑ       0          7
7999              ΧΡΥΣΟΥΛΑ       1          1
8000        ΧΡΥΣΟΥΛΑΕΙΡΗΝΗ       0          1
8001      ΧΡΥΣΟΥΛΑΕΛΙΣΑΒΕΤ       0          1
8002     ΧΡΥΣΟΥΛΑΕΥΑΓΓΕΛΙΑ       0          1
8003             ΧΡΥΣΟΥΛΗΣ       1          1
8004            ΧΡΥΣΟΦΙΛΗΣ       1          1
8005             ΧΡΥΣΤΑΛΛΑ       0          1
8006                 ΧΡΥΣΩ       0          1
8007                 ΧΥΣΕΝ       1          1
8008                ΧΥΣΕΝΙ       1          1
8009                 ΩΡΑΙΑ       0          1
8010             ΩΡΑΙΟΖΗΛΗ       0          2
8011             ΩΡΑΙΟΖΙΛΗ       0          1
8012             ΩΡΑΙΟΖΥΛΗ       0          1

[8013 rows x 3 columns]

In [95]:
def clearMinorities (data):
    toDelete = []
    
    for i in range(len(data)-1):
        #print("\t",i)
        if data.iloc[i]['Names'] == data.iloc[i+1]['Names']:
            if data.iloc[i]['Frequency'] > data.iloc[i+1]['Frequency']:
                toDelete.append(data.index[i+1])
            else:
                toDelete.append(data.index[i])
    return toDelete

In [96]:
toRemoveList = clearMinorities(data)
data.drop(data.index[toRemoveList],inplace=True)

data.drop('Frequency',axis=1,inplace=True)

print(data)

                       Names  isMale
0                      ΑΑΡΩΝ       1
1                       ΑΒΑΓ       1
2                    ΑΒΑΓΟΡΙ       1
3                      ΑΒΑΙΣ       1
4                     ΑΒΕΜΙΡ       1
5                     ΑΒΕΡΚΙ       1
6                   ΑΒΕΡΚΙΟΣ       1
7                     ΑΒΕΡΣΑ       0
8                   ΑΒΕΣΑΛΩΛ       1
9                   ΑΒΕΣΑΛΩΜ       1
10                      ΑΒΕΤ       1
11                     ΑΒΚΟΡ       0
12                      ΑΒΝΙ       1
13                       ΑΒΡ       1
14                    ΑΒΡΑΑΜ       1
16               ΑΒΡΑΑΜΘΩΜΑΣ       1
17                    ΑΒΡΟΒΑ       0
18                  ΑΒΡΟΚΟΜΗ       0
19                  ΑΒΡΟΤΕΛΗ       1
20                  ΑΒΤΑΝΔΙΛ       1
21                  ΑΒΤΑΝΤΗΛ       1
22                  ΑΒΤΑΝΤΙΛ       1
23                    ΑΓΑΒΝΗ       0
24                     ΑΓΑΘΑ       0
25                ΑΓΑΘΑΓΓΕΛΟ       1
26               ΑΓΑΘΑΓΓΕΛΟΣ       1
28                     ΑΓΑΘΗ       0
29                ΑΓΑΘΗΜΑΡΙΑ       0
30                ΑΓΑΘΟΚΛΕΙΑ       1
31                 ΑΓΑΘΟΚΛΗΣ       1
...                      ...     ...
7981  ΧΡΥΣΟΒΑΛΑΝΤΗΣΔΗΜΗΤΡΙΟΣ       1
7982    ΧΡΥΣΟΒΑΛΑΝΤΗΣΙΩΑΝΝΗΣ       1
7983            ΧΡΥΣΟΒΑΛΑΝΤΟ       0
7984           ΧΡΥΣΟΒΑΛΑΝΤΟΥ       0
7985    ΧΡΥΣΟΒΑΛΑΝΤΟΥΔΗΜΗΤΡΑ       0
7986            ΧΡΥΣΟΒΑΛΑΝΤΩ       0
7987           ΧΡΥΣΟΒΑΝΑΝΤΟΥ       0
7989             ΧΡΥΣΟΒΕΡΓΗΣ       1
7990                 ΧΡΥΣΟΠΗ       0
7991               ΧΡΥΣΟΠΗΓΗ       0
7992                ΧΡΥΣΟΠΙΑ       0
7993               ΧΡΥΣΟΣΤΟΜ       1
7994             ΧΡΥΣΟΣΤΟΜΟΣ       1
7995     ΧΡΥΣΟΣΤΟΜΟΣΓΕΩΡΓΙΟΣ       1
7996                  ΧΡΥΣΟΥ       0
7997                 ΧΡΥΣΟΥΛ       0
7998                ΧΡΥΣΟΥΛΑ       0
8000          ΧΡΥΣΟΥΛΑΕΙΡΗΝΗ       0
8001        ΧΡΥΣΟΥΛΑΕΛΙΣΑΒΕΤ       0
8002       ΧΡΥΣΟΥΛΑΕΥΑΓΓΕΛΙΑ       0
8003               ΧΡΥΣΟΥΛΗΣ       1
8004              ΧΡΥΣΟΦΙΛΗΣ       1
8005               ΧΡΥΣΤΑΛΛΑ       0
8006                   ΧΡΥΣΩ       0
8007                   ΧΥΣΕΝ       1
8008                  ΧΥΣΕΝΙ       1
8009                   ΩΡΑΙΑ       0
8010               ΩΡΑΙΟΖΗΛΗ       0
8011               ΩΡΑΙΟΖΙΛΗ       0
8012               ΩΡΑΙΟΖΥΛΗ       0

[7559 rows x 2 columns]

(8000:9819)