In [ ]:
import pandas as pd
import seaborn as sns
from copy import deepcopy
import numpy as np

from scipy import stats
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("Greek_Names.csv")

In [3]:
del data['isFemale']

In [4]:
start = 2
end = 4

In [5]:
for n in range(start,end):
    data['Column ' + str(n)] = data['Names'].astype(str).str[-n:]

In [6]:
data = pd.DataFrame(data.Names.str.split('-').tolist(), index = data.isMale).stack()
data = data.reset_index()[[0,'isMale']]
data.columns = ['Names', 'isMale']

In [7]:
data = data.drop(data[data.Names.map(len)<2].index)

In [8]:
data = pd.concat(g for _, g in data.groupby('isMale') if len(g)>1)

In [9]:
data = data.sort_values(by='Names')

In [10]:
data = data.reset_index(drop=True)

In [11]:
data

                    Names  isMale
0                   ΑΑΡΩΝ       1
1                    ΑΒΑΓ       1
2                 ΑΒΑΓΟΡΙ       1
3                   ΑΒΑΙΣ       1
4                  ΑΒΕΜΙΡ       1
5                  ΑΒΕΡΚΙ       1
6                ΑΒΕΡΚΙΟΣ       1
7                ΑΒΕΡΚΙΟΣ       1
8                  ΑΒΕΡΣΑ       0
9                ΑΒΕΣΑΛΩΛ       1
10               ΑΒΕΣΑΛΩΜ       1
11                   ΑΒΕΤ       1
12                  ΑΒΚΟΡ       0
13                   ΑΒΝΙ       1
14                    ΑΒΡ       1
15                 ΑΒΡΑΑΜ       1
16                 ΑΒΡΑΑΜ       1
17                 ΑΒΡΑΑΜ       0
18            ΑΒΡΑΑΜΘΩΜΑΣ       1
19                 ΑΒΡΟΒΑ       0
20               ΑΒΡΟΚΟΜΗ       0
21               ΑΒΡΟΤΕΛΗ       1
22               ΑΒΤΑΝΔΙΛ       1
23               ΑΒΤΑΝΤΗΛ       1
24               ΑΒΤΑΝΤΙΛ       1
25                 ΑΓΑΒΝΗ       0
26                  ΑΓΑΘΑ       0
27             ΑΓΑΘΑΓΓΕΛΟ       1
28            ΑΓΑΘΑΓΓΕΛΟΣ       1
29                  ΑΓΑΘΗ       1
...                   ...     ...
9812            ΧΡΥΣΟΠΗΓΗ       0
9813             ΧΡΥΣΟΠΙΑ       0
9814            ΧΡΥΣΟΣΤΟΜ       1
9815          ΧΡΥΣΟΣΤΟΜΟΣ       1
9816          ΧΡΥΣΟΣΤΟΜΟΣ       1
9817  ΧΡΥΣΟΣΤΟΜΟΣΓΕΩΡΓΙΟΣ       1
9818               ΧΡΥΣΟΥ       0
9819              ΧΡΥΣΟΥΛ       0
9820             ΧΡΥΣΟΥΛΑ       0
9821             ΧΡΥΣΟΥΛΑ       0
9822             ΧΡΥΣΟΥΛΑ       0
9823             ΧΡΥΣΟΥΛΑ       0
9824             ΧΡΥΣΟΥΛΑ       0
9825             ΧΡΥΣΟΥΛΑ       1
9826             ΧΡΥΣΟΥΛΑ       0
9827             ΧΡΥΣΟΥΛΑ       0
9828       ΧΡΥΣΟΥΛΑΕΙΡΗΝΗ       0
9829     ΧΡΥΣΟΥΛΑΕΛΙΣΑΒΕΤ       0
9830    ΧΡΥΣΟΥΛΑΕΥΑΓΓΕΛΙΑ       0
9831            ΧΡΥΣΟΥΛΗΣ       1
9832           ΧΡΥΣΟΦΙΛΗΣ       1
9833            ΧΡΥΣΤΑΛΛΑ       0
9834                ΧΡΥΣΩ       0
9835                ΧΥΣΕΝ       1
9836               ΧΥΣΕΝΙ       1
9837                ΩΡΑΙΑ       0
9838            ΩΡΑΙΟΖΗΛΗ       0
9839            ΩΡΑΙΟΖΗΛΗ       0
9840            ΩΡΑΙΟΖΙΛΗ       0
9841            ΩΡΑΙΟΖΥΛΗ       0

[9842 rows x 2 columns]

In [12]:
fdata = data[0:0]
data = data.values

In [13]:
names,isMale = np.hsplit(data,2)

In [16]:
tempIsMale = np.empty(0)
finalIsMale = np.empty(0)
tempNames = np.empty(0)
finalNames = np.empty(0)
for i in range(len(names)):

    if i == len(names) - 1:
        tempIsMale = np.append(tempIsMale,isMale[i])
        tempName = np.append(tempNames,names[i])
        finalIsMale = np.append(finalIsMale,stats.mode(tempIsMale))
        finaName = np.append(finalNames,np.unique(tempNames))
        tempIsMale = np.empty(0)
    else:
        if names[i] == names[i+1]:
            tempIsMale = np.append(tempIsMale,isMale[i])
            tempNames = np.append(tempNames,names[i])
        else:
            tempNames = np.append(tempNames,names[i])
            value = stats.mode(tempIsMale)
            finalIsMale = np.append(finalIsMale,value)
            finalNames = np.append(finalNames,np.unique(tempNames))
            tempIsMale = np.empty(0)

SyntaxError: unexpected EOF while parsing (<ipython-input-16-72781a52121c>, line 27)